;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="Skill.Block.Destruction",DevComment="")
GameplayTagList=(Tag="Skill.Cooldown.StickyBomb",DevComment="")
GameplayTagList=(Tag="Skill.Slot.1",DevComment="")
GameplayTagList=(Tag="Skill.Slot.2",DevComment="")
GameplayTagList=(Tag="Skill.Slot.3",DevComment="")
GameplayTagList=(Tag="Skill.State.Preview.Barrier",DevComment="")
GameplayTagList=(Tag="Skill.State.Preview.Construction",DevComment="")
GameplayTagList=(Tag="Skill.State.Preview.Destruction",DevComment="")
GameplayTagList=(Tag="State.Busy",DevComment="")

