;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="Skill.Block.Destruction",DevComment="")
GameplayTagList=(Tag="Skill.State.Preview.Barrier",DevComment="")
GameplayTagList=(Tag="Skill.State.Preview.Construction",DevComment="")
GameplayTagList=(Tag="Skill.State.Preview.Destruction",DevComment="")
GameplayTagList=(Tag="State.Busy",DevComment="")

