

#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

WINTER2025CORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Skill); // 스킬임을 표시하는 태그
WINTER2025CORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Skill_Casting); // 스킬 시전 중임을 시전자에게 부여하는 태그
WINTER2025CORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Skill_Preview); // Player.State.Preview

// 페이즈 관리를 위한 태그 선언
WINTER2025CORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Skill_BuffBarrier_Phase1); // 바닥에 범위를 표시한 상태
WINTER2025CORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Skill_BuffBarrier_Phase2); // 블록을 소환한 상태

WINTER2025CORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Player_State_Preview);
WINTER2025CORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Skill_State_Preview);

// 개편 이후

WINTER2025CORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Skill_Slot); // Skill.Slot

WINTER2025CORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Data_Damage);   // Data.Damage
WINTER2025CORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Data_Cooldown); // Data.Cooldown
WINTER2025CORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Data_RuneMultiplier); // Data.Cooldown